
init:
  - git clone -q --depth=5 --branch=master http://anongit.freedesktop.org/git/mesa/mesa.git C:\projects\mesa

  - rem Install pip
  - python --version
  - python -m ensurepip
  - rem Install Mako
  - python -m pip --egg Mako
  - rem Install SCons
  - rem XXX: "python -m pip install --egg scons" is too old (2.3.3)
  - rem appveyor DownloadFile http://prdownloads.sourceforge.net/scons/scons-local-2.3.4.zip
  - rem 7z x -oscons-local/ scons-local-2.3.4.zip > nul:
  - rem python scons-local/scons.py --version
  - python -m pip install --egg http://prdownloads.sourceforge.net/scons/scons-2.3.4.tar.gz
  - scons --version
  - rem Install flex/bison
  - cinst winflexbison -y
  - echo Path=%Path%
  - rem win_flex --version
  - rem win_bison --version
  - appveyor DownloadFile http://people.freedesktop.org/~jrfonseca/llvm/llvm-3.3.1-msvc2013-mtd.7z
  - 7z x llvm-3.3.1-msvc2013-mtd.7z > nul:
  - mkdir llvm\bin
  - set LLVM=%CD%\llvm
  - rem python scons-local\scons.py --version
  - rem python scons-local\scons.py MSVC_VERSION=12.0 llvm=1
  - scons MSVC_VERSION=12.0 llvm=1
