

version: 1.0.0.{build}

os: Visual Studio 2014 CTP4

configuration: Release

platform: Any CPU

shallow_clone: true

environment:
  LLVM: "C:/projects/install/LLVM"

init:
   - python --version
   - rem Install pip
   - mkdir "C:/projects/installer"
   - chdir "C:/projects/installer"
   - mkdir build
   # Download CMake
   - appveyor DownloadFile http://www.cmake.org/files/v3.2/cmake-3.2.3-win32-x86.zip
   - rename cmake-3.2.3-win32-x86.zip cmake.zip
   - 7z x cmake.zip > NUL:
   # Download LLVM
   - appveyor DownloadFile http://llvm.org/releases/3.6.1/llvm-3.6.1.src.tar.xz
   - rename llvm-3.6.1.src.tar.xz llvm.tar.xz
   - 7z x llvm.tar.xz > NUL:
   - 7z x llvm.tar > NUL:
   - python -m ensurepip
   # Download and install Mako
   - rem Install Mako
   - python -m pip install --egg Mako
   # Download LibXml2
   - python -m pip install lxml
   # Download SCons
   - python -m pip install --egg SCons
   - call "C:/MinGW/bin/mingw-get.exe install msys-flex msys-bison msys-wget"
   - appveyor DownloadFile "ftp://ftp.freedesktop.org/pub/mesa/10.6.0/mesa-10.6.0.tar.xz"
   - 7z x mesa-10.6.0.tar.xz > NUL:
   - 7z x mesa-10.6.0.tar > NUL:
   - mkdir LLVM
   - mkdir LLVM/buildDir
   - cmake/cmake.exe .. -G "Visual Studio 12 2013" "-DLLVM_USE_CRT_RELEASE:STRING=MT" "-DCMAKE_INSTALL_PREFIX:PATH=C:/projects/install/LLVM"
   - devenv.exe "LLVM.sln" "/Build" "Release" "/Project" "INSTALL"
   - python scons.py "build=release" "machine=x86" "MSVC_VERSION=12.0" "llvm=yes" "libgl-gdi"
   
before_build:
   - copy "C:\projects\installer\opengl32.dll" "C:\projects\fractalalgorithmsandbox\dependencies\opengl32.dll"

build:
  project: FractalAlgorithmTest.sln
  verbosity: minimal
