

version: 1.0.{build}

os: Visual Studio 2014 CTP4

configuration: Release

platform: Any CPU

shallow_clone: true

environment:
  LLVM: "C:/projects/install/LLVM"

init:
   - python --version
   - rem Install pip
   - mkdir "c:\projects\install"
   - chdir "c:\projects\install"
   - git clone https://gist.github.com/b80d5787925dc2b0231c.git "c:\projects\install\buildMesa"
   - python "c:\projects\install\buildMesa\buildMesa.py"
   
before_build:
   - copy "C:\projects\installer\opengl32.dll" "C:\projects\fractalalgorithmsandbox\dependencies\opengl32.dll"

build:
  project: FractalAlgorithmTest.sln
  verbosity: minimal
