
#llvm.org/releases/3.7.0/llvm-3.7.0.src.tar.xz

version: 1.0.{build}

os: Visual Studio 2014 CTP4

configuration: Release

platform: Any CPU

shallow_clone: true

init:

- cmd: >-
   - python --version
   - git clone -q --depth=5 --branch=master https://github.com/florianlink/MesaOnWindows.git C:\projects\installer
   - chdir "C:\projects\installer"
   - python buildMesa.py

build:
  project: FractalAlgorithmTest.sln
  verbosity: minimal
